"""empty message

Revision ID: 7e6351dd1121
Revises: d8dce9a4916b
Create Date: 2023-05-05 12:16:04.232009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6351dd1121'
down_revision = 'd8dce9a4916b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employee', sa.Column('first_allowance', sa.Integer(), nullable=True))
    op.add_column('Employee', sa.Column('second_allowance', sa.Integer(), nullable=True))
    op.drop_column('Employee', 'first_allownance')
    op.drop_column('Employee', 'second_allownance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employee', sa.Column('second_allownance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Employee', sa.Column('first_allownance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Employee', 'second_allowance')
    op.drop_column('Employee', 'first_allowance')
    # ### end Alembic commands ###
