"""empty message

Revision ID: d8dce9a4916b
Revises: 9f25b562f6a9
Create Date: 2023-05-03 22:03:42.714927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dce9a4916b'
down_revision = '9f25b562f6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    op.add_column('Department', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Department', 'Company', ['company_id'], ['id'])
    op.add_column('Employee', sa.Column('dept_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Employee', 'Department', ['dept_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Employee', type_='foreignkey')
    op.drop_column('Employee', 'dept_id')
    op.drop_constraint(None, 'Department', type_='foreignkey')
    op.drop_column('Department', 'company_id')
    op.create_table('Show',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Show_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], name='Show_company_id_fkey'),
    sa.ForeignKeyConstraint(['dept_id'], ['Department.id'], name='Show_dept_id_fkey'),
    sa.ForeignKeyConstraint(['emp_id'], ['Employee.id'], name='Show_emp_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Show_pkey')
    )
    # ### end Alembic commands ###
